#!/usr/bin/env bash
# script that displays a list of currently running processes
# show alls processes, for all users, including those which might not have a TTY
# Displays in a user-oriented format. Show process hierarchy

ps -auxf
