#!/usr/bin/env bash
# script that indefinitely writes 'I am alive!' to the file '/tmp/my_process'
# and pauses for 2 seconds in between them

for (( ; ; ))
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
