#!/usr/bin/env bash
#  script that loops from 1 to 10 using while loop and:
#  bad luck for the 4th loop
#  good luck for the 8th loop
#  Best School for the other

loop=1
while [ $loop -lt 11 ]
do
	if [ $loop == 4 ]; then
		echo $"bad luck"
	elif [ $loop == 8 ]; then
		echo $"good luck"
	else
		echo $"Best School"
	fi
	(( loop++ ))
done
