#!/usr/bin/env bash
# script htat displays numbers from 1 to 20 using while loop and:
# 4 and then bad luck from China for the 4th loop
# 9 and then bad luck from Japan for the 9th loop
# 17 and then bad luck from Italy for the 17th loop

loop=1
while [ $loop -lt 21 ]
do
	echo "$loop"
	case $loop in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( loop++ ))
done
